using UnityEngine;
using UnityEngine.UI;

public class Test2 : MonoBehaviour {

    public BoxCollider playAreaCollider;
    public bool pelialueenSisalla;
    public Transform pelaaja;

    private void FixedUpdate()
    {
        // Tarkista, onko pelaaja pelialueen sis채ll채
        if (playAreaCollider.bounds.Contains(pelaaja.transform.position))
        {
            Debug.Log("Pelaaja on pelialueen sis채ll채.");
            pelialueenSisalla = true;
        }
        else
        {
            Debug.Log("Pelaaja on pelialueen ulkopuolella.");
            pelialueenSisalla = false;
        }
    }
}
